### ISSUE TITLE
[r1cs] language feature tracking

### ISSUE THREAD

**Issue by chancehudson** [chancehudson/ashlang#27]
- [x] scalar math operations
- [ ] tuple inputs
- [x] let variables
- [x] re-assigned variables
- [x] static variables
  - [x] define static variables
  - [x] static variables as function arguments
  - [ ] static variables as loop condition
  - [x] static variables as function return values
- [x] function support
  - [x] `let` assignment
  - [x] `const` assignment (static evaluation)
  - [x] return function content directly
  - [x] arguments
- [x] function auto-import
- [ ] if statement
  - [ ] equality
  - [ ] block support
- [ ] general block support
- [x] builtin functions
  - [x] `assert_eq`
  - [x] `crash`
- [ ] vector support
  - [ ] vectors of any dimension e.g. `v[2][3][4][1]`
  - [ ] vector variable support
  - [ ] vector constants support
  - [x] vector math support
  - [ ] vector index access by variable
  - [ ] vector index ranges e.g. `[0..5]`
  - [ ] vector binary operation support
  - [ ] vector support in functions
  - [ ] vector support as function argument
  - [ ] vector support as function return
  - [ ] vector index access by variable e.g. `v[i]`
- [ ] loops

**Comment by chancehudson** [comment]
Closing in favor of readme checklist
