### ISSUE TITLE
[tasm] language feature tracking

### ISSUE THREAD

**Issue by chancehudson** [chancehudson/ashlang#4]
- [x] scalar math operations
- [x] tuple inputs
- [x] let variables
- [x] re-assigned variables
- [x] static variables
  - [x] define static variables
  - [x] static variables as function arguments
  - [x] static variables as loop condition
  - [x] static variables as function return values
- [x] function support
  - [x] `let` assignment
  - [x] `const` assignment (static evaluation)
  - [x] return function content directly
  - [x] arguments
- [x] function auto-import
- [x] if statement
  - [x] equality
  - [x] block support
- [ ] general block support
- [x] builtin functions
  - [x] `assert_eq`
  - [x] `crash`
- [x] vector support
  - [x] vectors of any dimension e.g. `v[2][3][4][1]`
  - [x] vector variable support
  - [x] vector constants support
  - [x] vector math support
  - [x] vector index access by variable
  - [ ] vector index ranges e.g. `[0..5]`
  - [ ] vector binary operation support
  - [x] vector support in functions
  - [x] vector support as function argument
  - [x] vector support as function return
  - [x] vector index access by variable e.g. `v[i]`
- [x] loops

**Comment by chancehudson** [comment]
Closing in favor of readme checklist
